version: "3.9"
services:
  # XSS Hunter Express service
  xsshunterexpress:
    build: .
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      # Directory where payload fire images are stored.
      - ./payload-fire-images:/app/payload-fire-images
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/gcloud.json
  postgresdb:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-db-data:/var/lib/postgresql/data/pgdata
